name: Auto Pull Request
on:
  push:
    branches-ignore:
      - master
      - nix-on-droid

permissions: write-all

jobs:
  auto-pull-request:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup git
      run: |
        git config --global user.name 'little fmway'
        git config --global user.email 'fm18lv@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Refresh Git Remote
      run: git fetch origin
    - name: Refresh Your Head
      env:
        BRANCH: ${{ github.ref }}
      run: |
        git rebase origin/master "$BRANCH"
        git push origin "$BRANCH" --force
    - name: Check if PR exists
      id: check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: ${{ github.ref }}
      run: |
        prs=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --head "$BRANCH" \
            --base 'master' \
            --json title \
            --jq 'length')
        count_commit=$(git rev-list --left-right --count origin/"$BRANCH"...origin/master | awk '{print $1}')
        if (( prs > 0 )) || (( count_commit < 1 )); then
            echo "skip=true" >> "$GITHUB_OUTPUT"
        fi
    - name: Create Pull Request
      if: '!steps.check.outputs.skip'
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH: ${{ github.ref }}
      run: |
        gh pr create --title "Merge From $BRANCH" --body "" -l "automated" 
