name: "test"
on:
  # Only trigger, when the build workflow succeeded
  workflow_run:
    workflows:
      - cachix
    types:
      - completed
jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-experimental-features = nix-command flakes repl-flake auto-allocate-uids configurable-impure-env
    # - uses: cachix/cachix-action@v14
    #   with:
    #     name: fmcachix
    #     # If you chose API tokens for write access OR if you have a private cache
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: add cachix
      run: |
        nix profile install nixpkgs#cachix
        cachix use nix-community
        cachix use devenv
    - name: build
      run: nix build .#nixosConfigurations.Namaku1801.config.system.build.toplevel
    - run: nix-collect-garbage -d
