name: "test"
on:
  pull_request:
  push:
permissions:
  contents: read
  id-token: write
jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        extra-conf: |
          experimental-features = nix-command flakes pipe-operators repl-flake auto-allocate-uids configurable-impure-env
          substituters = https://cache.nixos.org https://cache.nixos.org/ https://devenv.cachix.org https://fmcachix.cachix.org https://nix-community.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= fmcachix.cachix.org-1:Z5j9jk83ctoCK22EWrbQL6AAP3CTYnZ/PHljlYSakrw= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build
      run: nix build .#nixosConfigurations.minimal.config.system.build.toplevel --verbose
    - name: Info
      run: nix path-info -Sh ./result
    - run: nix-collect-garbage -d